DROP DATABASE IF EXISTS Bookish;
CREATE DATABASE Bookish;
GO 

USE Bookish;

CREATE TABLE users(
	User_ID int NOT NULL PRIMARY KEY IDENTITY(1,1),
	Name VARCHAR(255),
	UserName VARCHAR(255) NOT NULL, 
	Password VARCHAR(255)
);

CREATE TABLE book(
	Book_ID int NOT NULL PRIMARY KEY IDENTITY(1,1), 
	Name VARCHAR(255) NOT NULL, 
	Author VARCHAR(255) NOT NULL, 
	Genre VARCHAR (255) NOT NULL, 
	isbn int NOT NULL
);

CREATE TABLE copies (
	copy_ID int NOT NULL PRIMARY KEY IDENTITY(1,1),
	Books_ID int NOT NUll,
	FOREIGN KEY (Books_ID) REFERENCES book(Book_ID),
	Borrowed_By_ID int,
	FOREIGN KEY (Borrowed_By_ID) REFERENCES users(User_ID),
	Due_Date DATE
);